title: Stu
description: Your friendly tree-planting companion developed by Arbor Robotics at CMU.
theme: just-the-docs

color_scheme: arbor # see _sass/

url: https://just-the-docs.github.io
# logo: "/assets/images/arbor-logo.png"
favicon_ico: "/assets/images/arbor-logo.png"

callouts:
  extra:
    title: Extra Info
    color: blue
  important:
    title: Important
    color: yellow
  warning:
    title: Warning
    color: red
  new:
    title: New
    color: green

aux_links:
  "Github Repo":
    - "https://github.com/arbor-robotics/steward"
